### ISSUE TITLE
[sync] Heavy theme generated by sync plugin with default values

### ISSUE THREAD

**Issue by sassanh** [mui/mui-design-kits#416] opened 2024-11-19 12:17 UTC
### Steps to reproduce

Steps:
1. Go [here](https://www.figma.com/community/file/912837788133317724) and open it in Figma
2. Go [here](https://www.figma.com/community/plugin/1336346114713490235/material-ui-sync) and open it in the project you created in the previous step
3. Generate the theme

### Current behavior

It generates this: https://gist.github.com/sassanh/b288daefed6f4b5d130971484ca9fb1a

### Expected behavior

I expect it to create something like `{}` or maybe with headers of each section like `typography`, `palette`, etc.
I think it shouldn't generate such huge object for an unmodified fresh project.

From the [documents](https://mui.com/material-ui/design-resources/material-ui-sync/):
A theme containing the **altered** tokens is generated and displayed in the plugin's Theme tab.

but it is exporting unaltered items too.

### Your environment

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v6.1.0                |
| Design tool         | Figma |

**Search keywords**: sync theme

**Comment by rkristelijn** [comment] 2024-11-22 08:41
Hi @sassanh I've created a similar question https://github.com/mui/mui-design-kits/issues/418 so I'm reading along when you get a response

**Comment by oliviertassinari** [comment] 2024-12-22 18:13
Duplicate of #428

**Closed** 2024-12-22 18:13 UTC
Labels: figma, duplicate, scope: sync
