### ISSUE TITLE
[figma] The paddings seem to be broken

### ISSUE THREAD

**Issue by sul-patompong** [mui/mui-design-kits#204] opened 2023-07-07 07:58 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:
1. Publish the downloaded from a purchased file.
2. Use either Button, Navbar and etc. from the assets.
3. The alignment looks weird as in the screenshot.

<img width="1012" alt="Screenshot 2566-07-07 at 14 56 01" src="https://github.com/mui/mui-design-kits/assets/20871567/ebef8844-6ffd-41e3-ae6f-a6795643c5b6">

### Current behavior 😯

The alignment looks weird as in the screenshot. 

### Your environment 🌎

| Software            | Version               |
| ------------------- | --------------------- |
| Design file version | v5.11.1                |
| Design tool         | Figma |
| etc.                |                       |

**Comment by adrianmanea** [comment] 2023-07-07 08:39
We received another complain about this exact issue but seems I can't replicate it.

https://github.com/mui/mui-design-kits/assets/5917515/db3b62bf-d84b-4681-bbda-40389ba3db36

**Comment by sul-patompong** [comment] 2023-07-07 08:47
@adrianmanea I checked on the overview page. It also happens the same thing.
<img width="1656" alt="Screenshot 2566-07-07 at 15 45 13" src="https://github.com/mui/mui-design-kits/assets/20871567/82ec8417-addd-4120-9079-1d81b15ed462">

**Comment by sul-patompong** [comment] 2023-07-07 08:49
Does it possible that the file you uploaded on the Mui store is incorrect?

**Comment by adrianmanea** [comment] 2023-07-07 08:54
Something is definitely off with the main file. Would you mind Deleting and Importing it again and see if you get different results?

**Comment by sul-patompong** [comment] 2023-07-07 08:57
> Something is definitely off with the main file. Would you mind Deleting and Importing it again and see if you get different results?

Yes, I did it multiple times. Also doesn't work

**Comment by adrianmanea** [comment] 2023-07-07 09:02
Okay. Could you please send me an email with the order ID so that I can provide you with a temporary link to the library we are currently working on? The library is fully based on variables. Email: adrian.manea@devias.io

**Comment by leticialourenco** [comment] 2023-07-09 03:32
Also experiencing this issue, from old and fresh downloads v5.11.1

**Comment by adrianmanea** [comment] 2023-07-09 09:30
The customer reports that the bug persists even after the Variables update. The issue appears to be that the components lose their top and left paddings. @leticialourenco , which environment did you use to import the file? Was it the Beta app or the stable version?

**Comment by AlaaSubora** [comment] 2023-07-09 17:51
I also have the same issue 

https://github.com/mui/mui-design-kits/assets/27156065/ad03a699-288f-4f7e-a60d-2ecae683ee9a

**Comment by AlaaSubora** [comment] 2023-07-09 17:59
I just tried it with a fresh Figma account and the issue is still there. It seems that it's with both the Core and the Joy UI file!

**Comment by AlaaSubora** [comment] 2023-07-10 10:48
When comparing your screen with mine the individual padding seems to be causing the problem. when a new button the individual padding is automatically checked leading to the problem. deselecting the checkmark and changing the values manually the components seem to turn normal. hope that helps with figuring out the issue
![image](https://github.com/mui/mui-design-kits/assets/27156065/e3f82e82-e7e7-4de6-b503-bec82b653d65)

**Comment by storms-lab** [comment] 2023-07-10 14:00
I am also having this issue. I have a fresh new Figma account and just imported MUI 5.11.1 as a library, but the padding is off when I use the button component (haven't tested others). Interestingly, however, the padding in the design file seems to be correct.

![image](https://github.com/mui/mui-design-kits/assets/51679664/0f05d230-bcef-4b75-aa59-ba9b81ae785e)
![image](https://github.com/mui/mui-design-kits/assets/51679664/f9997039-cce9-43dc-944c-a89cd98c7650)

**Comment by adrianmanea** [comment] 2023-07-13 07:35
**As a temporary solution**
Since our master library does not have this bug, we can can make individual copies and transfer ownership to you.

To do so, follow these steps:

1. Send an email to [[figma@mui.com](mailto:figma@mui.com)](mailto:figma@mui.com) with the Figma account email you want us to share the library with and the order ID.
2. Accept the invitation we send you.
3. We will transfer the ownership rights to you.
4. Duplicate the library and move the newly duplicated copy to your organization or drafts. We will delete the original file after 72 hours.

**Comment by adrianmanea** [comment] 2023-07-13 11:37
**As a temporary solution**

Since our master library does not have this bug, we can can make individual copies and transfer ownership to you.

PS. We have confirmed just one or two copies so far, we are not 100% if the issue will persists this way too.

To do so, follow these steps:

1. Send an email to [[[figma@mui.com](mailto:figma@mui.com)](mailto:figma@mui.com)]([mailto:figma@mui.com](mailto:figma@mui.com)) with the Figma account email you want us to share the library with and the order ID.
2. Accept the invitation we send you.
3. We will transfer the ownership rights to you.
4. Duplicate the library and move the newly duplicated copy to your organization or drafts. We will delete the original file after 72 hours.

**Comment by adrianmanea** [comment] 2023-07-17 12:13
Great news, Figma announced that they fixed the import bug!

> The bug has been fixed as of yesterday evening, so if you re-import your file(s) you should see the correct paddings. Sorry for any disruption this may have caused!

**Comment by adrianmanea** [comment] 2023-07-18 15:34
I think we can close this issue since it's fixed.

**Closed by adrianmanea** 2023-07-18 15:34 UTC
Labels: figma, bug 🐛, regression
