### ISSUE TITLE
Button with icons

### ISSUE THREAD

**Issue by amitquest** [mui/mui-design-kits#412] opened 2024-11-07 12:08 UTC
### Steps to reproduce

Link to live example: https://www.figma.com/design/lNGFVHPHGplTStkVyH6uZ1/MUI-for-Figma---Buttons-with-icons-height-and-vertical-centre-issue?node-id=3-204&t=NHs6Xu5Qr22onwdl-1

Steps:
1. Drop button, change size to small, change to outline enable both icons

### Current behavior

1. The icons in the Small/Medium Outline and Text buttons are not in the vertical center.
2. The size of the Small button height increases from 30 to 32 when the icons are enabled.

### Expected behavior

1. The icons should be in the vertical center in Small/Medium Outline/Text buttons
2. The Small Solid/Outline/Text button height size should remain 30px when the icons are enabled.

### Context

Design height and vertical alignment consistency similar to MUI 

### Your environment

| Software | Version |
| ------------------- | --------------------- |
| Design file version | v5.17.0 |
| Design tool | Figma |

**Search keywords**: Button Medium/Small vertical alignment with icons and Small button height with icons

**Comment by adrianmanea** [comment] 2024-11-11 08:49
Hi, we are aware of the problem! Here's the open issue associated with this: https://github.com/mui/mui-design-kits/issues/408

**Comment by oliviertassinari** [comment] 2024-12-22 17:54
Duplicate of #408

**Closed** 2024-12-22 17:54 UTC
Labels: figma, duplicate
