### ISSUE TITLE
Non-conforming grid layout(s)?

### ISSUE THREAD

**Issue by moorefficient** [mui/mui-design-kits#60] opened 2022-05-17 20:55 UTC
For example, the XS layout doesn't seem to fit the standard MUI 12-col grid. (See attached.) 

But what's even more strange is that the overall design file doesn't seem to conform to the actual Material Design grid system. (I understand if MUI is just keeping in sync with MUI--and not actually the Material Design spec--but even then, e.g. the XS layout seems off.) I also don't think the gutters should exceed the column widths, right? (I assume that's why the Material Design spec drops down to a 4-col grid on XS...)

<img width="845" alt="Screen Shot 2022-05-17 at 1 43 13 PM" src="https://user-images.githubusercontent.com/104411166/168907235-23413054-643f-4e34-a35c-024a8a1a4f06.png">

Can you please advise on the intention here, and what the rationale for that layout grid is? Thanks!

**Comment by adrianmanea** [comment] 2022-05-18 11:57
Layout components are designed to be used as starting points for different breakpoints https://mui.com/material-ui/customization/breakpoints/#default-breakpoints - just drag and drop one of the layouts you'd like to start with, detach and use it as your base artboard.

**Comment by oliviertassinari** [comment] 2022-05-26 17:09
> don't understand why e.g. XS doesn't conform to the MUI spec

@moorefficient Could you expand on what you have in mind? I'm not following what's the expected behavior. What would following Material UI (`@mui/material`) looks like in our context? Thanks

**Comment by moorefficient** [comment] 2022-06-02 21:18
@oliviertassinari  - sure: all I meant was that I would've expected the XS grid layout to match the spec; 
in this case, to have 12 columns adjusted across the XS layout, with realistic/expected gutters and margin. 

You'll notice in the screenshot above that you can only count 11 columns. 

(Honestly, I found it slightly odd that MUI used 12 cols on XS, anyway, whereas I believe the original [Material Design spec recommends 4 col on e.g. the 360 dp breakpoint](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins). But that's another story!)

**Comment by oliviertassinari** [comment] 2022-06-04 21:36
> You'll notice in the screenshot above that you can only count 11 columns.

@moorefficient Ahhh right, thanks now I get it. There are indeed two problems:

1. There are only 10 columns displayed. This can be solved with the next point ⬇️
2. The gutter between each column is too big. At this width, it should be 16px but not 24px.

> Material Design spec recommends 4 col on e.g. the 360 dp breakpoint

This is true but I think that it depends on who we want to optimize for. The React components use 12 columns regardless of the screen width. So maybe a designer using a layout of 12 columns while still follow in the 4 columns guideline of Material Design might help the developer to implement the design.

**Comment by adrianmanea** [comment] 2022-06-09 08:39
Now it makes sense, there is indeed a problem with the columns! This will be fixed in the upcoming update, we should be more cautious with counting the columns. Until then can you please follow what @oliviertassinari said:
1. Go to the Extra Small guides and edit the count to 12
2. Width to 14

Sorry for the trouble and thanks for reporting this.

**Comment by adrianmanea** [comment] 2022-07-19 06:54
Closing this thread since I've answered here: https://github.com/mui/mui-design-kits/issues/68

**Closed by adrianmanea** 2022-07-19 06:54 UTC
Labels: figma, bug 🐛
