### ISSUE TITLE
[figma] Data Grid tree data

### ISSUE THREAD

**Issue by oliviertassinari** [mui/mui-design-kits#330] opened 2024-04-10 19:42 UTC
### Summary

> Could you please add this in the FIGMA Design kit as a separate example from the Row Grouping?

Sent from https://mui.com/x/react-data-grid/tree-data/

**Search keywords**: -

**Comment by danilo-leal** [comment] 2024-04-12 11:50
Duplicate off https://github.com/mui/mui-design-kits/issues/331 — closing it

**Closed by danilo-leal** 2024-04-12 11:50 UTC
Labels: figma, status: waiting for maintainer
