### ISSUE TITLE
You have a new comment on Material UI for Figma (and MUI X) by Yuli

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#323] opened 2024-03-28 19:22 UTC
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfK7-2Bc-2FvyTtgXEWluQ-2B0JSYy9UVc7R80pVwZOI5JuN0p13g51hdAPvAl-2F0vrualIBcJygMBzwyKIORfxi0JaeLN0-3DuGn2_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2xrSeTAqpkQUA9owGaA9Oy3nZ1hEkRyJasWAneMiLvAJp7pgHhE4TYAyxTNMJCTWSn-2BCF67qp-2BSp-2FW1GvTVFdJTN4TEjAQVER3Fd-2BJb3kYqCftP6dJYLN7-2BubZ6fKOpjxswcpOdmIfwE7c8uIqEDPCrAPzv0bSLuhovL7WLEECQmEKY0JFGV03eEhIe1p4H8bflljcB8Nj8nPnJF-2FaiqZj4PImWU9f8s8-2BftLlBhWTmg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>Material UI for Figma (and MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfG93-2B9AEWcSqcmLkSLJMZ6j3CYJ9p4jtQL9uODLFkwiJVz2b_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2xrSeTAqpkQUA9owGaA9OyucbCw0XA71EuLYmzivsNXukSgRJlG0NXCnXLATx1TevSzG0JO94kdGtHgTUzHoNdvre3xrax-2FqSS7v-2Fm89qZ-2BZYSOdKsVOqDmozbVPDCajL-2B2mmzw461pAR-2F1vk2YUheD61B6WUNJuV-2Bbrs1acA9lF8Gnz5c8XPty0pE-2BTlaY4PE-2BTih2V1Ftzf2H3MsrSLsUCAZ-2FqABwi8jIDv5Qbctwg-3D-3D"
><img
src="https://www.gravatar.com/avatar/2e1627457fb6c6f98e5dd8328f97925d?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_y_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfG93-2B9AEWcSqcmLkSLJMZ6j3CYJ9p4jtQL9uODLFkwiJlSmD_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2xrSeTAqpkQUA9owGaA9OyVMDf9dY6sMLe2qkLJXAnS-2B0jzfGmJC4n27GroxBEWR0pbH-2FGKRNT50XLgT72J3uONKv8o9sX59sRNb9N8A9lA9XXH7Gz4wB2mX6aegtNt-2FTR2cUNWshR62ICO-2Fco-2BvNfiW27cKpxRPiLO4Xh4aOd2JoGHIfRT7mKdqPhZbWaCndmxvl6kZcBtpBwEHIIAMPDIYs0SBWeRgHYMQ42EConMQ-3D-3D"
>Yuli</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi goadrian  thank you for your amazing job. May I ask 2 questions:
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfKIZY6q-2FLhdz5Eu8PgcuW6iIDdKv77x76gq9gdMxo54FtkUiOM1IWJhe2wn6UH-2FS6U5jRj1LBx5eEnaqzFt0MmW1gbSS0f2TRbtGJ7oePWRqwS2y_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2xrSeTAqpkQUA9owGaA9OypZSVkFTy1aPkJgHxEY0Lc8EGLDBK4tXlw-2BaevxGp2R1QnZX4z-2FbJPibSbyIbF0RUTlgzyWQTQnUmX-2BBcTn4zJUqTALcdepQyeWl6agXlstYZlqiCud87vTabVMR43oCiqaipWfiAeOkPY8VUveQIg7iM-2F7-2B966jAVKuuVUTuOizhCa4jVhj7Eziokw5DHLWEyl4rtd8rq5PynJxTAYwOdw-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by adrianmanea** [comment] 2024-03-29 10:15
Answered on community:
> Hi [@yuliaerokhina1](https://www.figma.com/@yuliaerokhina1) for the first question we want to keep the features as native as possible. We have a dedicated video on how to work with variables: https://youtu.be/vpC-cMbjgpQ
Most components do not use the spacing variables, they hard-coded. I'm not sure if this was intended or not (in the API components).

@DavidCnoops is it possible to update the the description of the Figma product with the video I'm linking in comments?

**Comment by adrianmanea** [comment] 2024-04-26 15:05
Closing this since we've solved the problem!

**Closed by adrianmanea** 2024-04-26 15:05 UTC
Labels: figma
