### ISSUE TITLE
New comment on MUI for Figma (Community) by Rachana Pandey

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#186] opened 2023-05-21 00:06 UTC
<tr>
<td align="left" style="padding: 0 0 36px">
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6iNogAVanEscp0loLKSYLl5InJ-2F4vBf4mY5jN1MJL8jGUcuzCFNEbp3NMAuKslu7t7cZKhViRYQpd7Y6nHO7No-3DdAE1_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOUZIYn0UW3HEL-2F167qf8z5GhZROHAMOx2Qpd2UQrqaf6LnjvB2BQsz2duhKrI3izMPz061-2BlwM5r17nfqJ54kRrLg0YQXmOdt3WnNCKqA8SEs3DsR-2F1z0C50L-2BleYrw1Jahn3nyUzufMKhzCREWZH-2BoFeA-2BuoVJO6N9NjjPyTwnm8-2BY5txr3mcnOZmKknvzmDkua7ejJ0TP6rfUMmov5k2OHC-2FNLzuMadkD-2FXdHjt4cg-3D-3D"
>
<img
src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390"
width="65"
style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
"
alt="Figma"
/></a>
</td>
</tr>
<tr>
<td
class="wi-100p pb-30"
align="center"
style="padding: 0 0 52px"
>
<img
src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792"
width="392"
style="width: 392px; vertical-align: top"
alt=""
/>
</td>
</tr>
<tr>
<td
class="pb-30 plr-8 fs-24 lh-28"
align="center"
style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
"
>
You have a new comment on <strong>MUI for Figma (Material UI, Joy UI, MUI X)</strong>
</td>
</tr>

<tr>
<td
class="ptb-20 plr-25"
style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
"
>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6pY7BO46KZ0a173-2BXZnr6l1VWHcHXNXSZ7WmeM3ZX9u4bP1_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOUZIYn0UW3HEL-2F167qf8z5o9YhcFA5pxxhrZuIkKblv2U8UsjzvWyEL-2BaLzwZ-2FiAbDuKoGJaUyAC2yTNFn-2F348Szjm506xtXFayH3BTO0Bd0HhgY-2B6K95DK864b2fjBxsRDE3vfvkCzETPDirpotWilVXfQ-2FfYsggDkfOq3txxat9ge8QDO6sbH8-2FhRZkO65ytGWKfrx8Dnt1fhyoS3LE-2F6i9l2EPiQRhyE8Ytu7F5WA-3D-3D"
><img
src="https://www.gravatar.com/avatar/08ca3f893a28d92b2ba9487c211ef3bc?size=240&default=https%3A%2F%2Fs3-alpha.figma.com%2Fstatic%2Fuser_r_v2.png"
style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
"
alt=""
/></a>
</td>
<td
style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
"
>
<a
style="text-decoration: none"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro6pY7BO46KZ0a173-2BXZnr6l1VWHcHXNXSZ7WmeM3ZX9uAShG_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOUZIYn0UW3HEL-2F167qf8z5N1FYmqSlWpnR4yBOh-2F0kLy08UcZIrS2SPdrZr3uKrYPXro2vK79us0aVohxubzbaXZBL-2F-2B3TSBv1pLgXMaEJwJC2G4cmJ4NEWw4tvj3o-2FHBvic16sDL0ko9UQH-2F0kk4WycEbNSAt5NAlbyi3-2BWxNaacirUNOVV7UPkqrif2BDgbTu1ohqGmT0TBEYunVgUJFH22NhLLJU0HKZSMITczYPA-3D-3D"
>Rachana Pandey</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td
style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
"
>
Hi, I purchased  Figma for Mui 5.11. but I don&#39;t see the file for Dark mode. (Previously when I had purchases Figma for UI 5.0.1 I remember we got access to both Light and dark mode files)
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table
width="223"
align="center"
style="margin: 0 auto"
cellpadding="0"
cellspacing="0"
>
<tr>
<td
class="active-t"
align="center"
style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
"
>
<a
style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
"
href="https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro4E-2BcQSymBgTjggzBoDby3TU8J4pVOtpHZoC6kA5FhtgK7JcYMS3WcveuayJlaIOfBIVlW2N2tvAefPYuWlb2wTOfAIifx4zcUqJ2I6nyaXT00t5_Df0Lc06qysIgHsGk0xVMarlz8H-2BTeQTPLKs46dH9UmOUZIYn0UW3HEL-2F167qf8z5GQDEDknmaYtvG01jaXP3JIanfAX349KhC2kN2RY7O7V1ksHRIBeCwf5qfnPudx7itOEWplQ0tAXDj38TD4htXAcPcVhYKDULINCrikiKmUJpSNvsc9LG8IGh0IKKqDvsHdoHvGJYRapoIjWVLidIR055nFzGl3pvc7v6VMiO2FMIQKM-2BsW0-2BDtVb9I04JqS9s7X-2BFHiylE0ywQ5dKhGCOA-3D-3D"
>Reply to comment</a
>
</td>
</tr>
</table>
</td>
</tr>

**Comment by oliviertassinari** [comment] 2023-05-21 11:12
Duplicate of #187

**Closed by oliviertassinari** 2023-05-21 11:12 UTC
Labels: figma, duplicate
