### ISSUE TITLE
[question] sync design tokens from Figma to React

### ISSUE THREAD

**Issue by vonsa** [mui/mui-design-kits#174] opened 2023-04-10 12:44 UTC
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi, I purchased the MUI Figma design kit yesterday.
I'm trying to adjust the design token values in Figma and then export the design tokens using Token studio for Figma.

**Expected:**
I can export or sync the design tokens to my React/Next.js project and apply the theme without assigning the values manually.

**Actual:**
The exported format does not seem to match the theme configuration that the ThemeProvider accepts. I can't find documentation on how to sync the Figma theme to React/Next.js.

### Your environment 🌎

The design file was supplied yesterday, so I assume it's the latest.

"dependencies": {
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/material": "^5.11.16",
  },

**Comment by oliviertassinari** [comment] 2023-04-11 10:28
Duplicate of #10

**Comment by oliviertassinari** [comment] 2023-04-11 10:29
Indeed, today, it involves manual works it map the values correctly.

**Closed** 2023-04-11 10:29 UTC
Labels: duplicate, support: question
