### ISSUE TITLE
You have a new comment on Material UI Sync by Katie Pang

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#395] opened 2024-09-04 17:42 UTC
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsXFUJiSwFCvzNG8GRHcugTvPjzLeSMsnjKrWmeWDb7y-2BhzVWVZau-2FgSOuH0VeY2oTA-3D-3DwC6V_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2cu3kJF-2BgyKSsAvB0sUgCD4ejGpJhMTR02FGdErm3E-2FYWUKTm1KG-2FqYhvLzj5awrjZ6inssaCmQQ2VH3tgL96FHbK0aUmamW1zzeok4MOQKbOWIe5SZJEvfQDSJvppj4GEPj2j2cXWn4yE4MW9NMNGrPcyhmzq6pg-2BnOd6MuU6WS8vpUD2NAMQ3cDOPdwa5F3qheTb26lddu9-2B9wfwz1qDwDss31s-2F0il4wn3O2Y9Hk7CeTdtHFQVTiPq971NrJAtclTeLFMdSQvWh1p5LkTfMN8OOSLWBdWD0Z-2FHC6XgQ-2FA-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI Sync</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRX0PII-2FisgdGOOIckipCVOimOma9mpCH6Ud7Q-2FQ8ebgfO4aa4G4YkCS2CZaPCqG3g-3D-3Dr2MI_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2cu3kJF-2BgyKSsAvB0sUgCDuzTuwgx4m2gH3hyA6U3Vf5vImDgMpy0jcrM9HA7s1X-2BY2LkUGEbu99Z4F5zCRhWJgXu36hrO3LxQJE5e7RUScgSJ9QvOq7V4Z0MtJJJPX562KsnqMrvR3TQ0KT65BxoN-2BnYSoBk57lsB-2BvqU0qtM1VPFSD3VYxMhPEAmbdbDyKE7pJO9PpyW8jrG4duE0MwCRZskE3iMeCwJO7RaUqEG0TmacBiyzA-2BGA3XGmrAoRYoJbCtGknmRk6krLiwQdEeq3g-2FUEfmv84NFBIV0PnNZsQ-3D-3D"><img src="https://s3-alpha.figma.com/profile/714a4d4c-02a6-487e-b95b-1fd8d68e36d6" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsRX0PII-2FisgdGOOIckipCVOimOma9mpCH6Ud7Q-2FQ8ebgfO4aa4G4YkCS2CZaPCqG3g-3D-3D0DC__xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2cu3kJF-2BgyKSsAvB0sUgCDLq4kBpPi-2BbUsvf-2B9RMBzXZZbECmQAxN0FrC68A3C-2BSChA43YuQglOMGXa770dHjqY98qFl-2FQjwEOm-2FbX3Z21ZsWFrJ6fWAhGllHjQxYQaPPDRFks-2B9I8ghgyN2y-2FZl4EyLwptyhw4Z3TglpuWlhSuhtZiI4RO3e3glN0euSazJXOR04nTz-2FnqHPC2OPccngMEelI35uOD54AAh6jdRcZHKHDgDdJMHDQ3bD6sSB2P5Hhf2Kdtyll3JyuavsWFNlXVTyLrnSdIaQJlH2jcNhzcQ-3D-3D">Katie Pang</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Would be awesome to get to use this plug in but given that it only generates 3 components, it makes it much harder to implement at the moment. Thanks!
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsfKULVpw-2FrEp6bHOY6Q69g0X6ILKplT7Y6Q-2BlVtX9Wc-2B4cd-2FRuznvao7Q-2Bkvvbxxsw-3D-3DSJnn_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2cu3kJF-2BgyKSsAvB0sUgCDdC93jw6uDBHic1pHuSITq5rdU-2FBwIQP-2BCzSvbRe7lDlAl6bhbI3h6RIs50fcxHVya-2FpOoo2lgAax3aYWRtk-2BlmhUI8zAwC02i5YPpu-2B-2Bx-2BTE-2FCgLxRNmTsorcDjiYBisuVBz0VH6xDXldXwnweFKtTM13IODHlwOtza5Z7YpC4ZXEp-2BLRmmCH7e4uKWyujnebHuzEJyRfpBXOmdQS194CsJF4qHliQALHrRsQ9bSxTQE9-2FgVWOSrNCXtrtg2RQ7mKlmR-2FwLEJEh-2BpLSd616ZZg-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Search keywords**:

**Comment by oliviertassinari** [comment] 2024-10-03 23:32
Duplicate of #337

**Closed** 2024-10-03 23:32 UTC
Labels: figma, duplicate, scope: sync
