### ISSUE TITLE
[MUI Sync] Only supporting 3 components

### ISSUE THREAD

**Issue by mui-bot2** [mui/mui-design-kits#391] opened 2024-08-30 14:52 UTC
<tr>
<td align="left" style="padding: 0 0 36px">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsQq4jMmSNlu9GMJOWaD3MNW3kaFzRgwKNz8Vvo9e543iXD8vihzZoKltNHgt6AcIjg-3D-3D89Ks_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2IEKsYWjkDOI0BcvC-2B4WI8v-2FjbSblO85PNsYUL3C-2FBKdBWqqRm-2B4qyJHJ9WMaODUaxUCBIIs0OSUXDT8SrEsxB-2FxDzVDyT-2B0Z3u2IuWVbVt1i-2FOQxZrK9h-2BplXN131b708FCzCa5xA9lDF6kr-2FdQFbKEiE-2FYcYLgTwtMgLHS-2F0miCLsVcc0pN3L-2Bk-2BWeSqekpF2z-2F-2B6Up2-2FR4Dbs7gFCZULvnfba7MMlNcqAr0jukWMhMMW8tWwDxSGSTIbakQUBNPwczSZhPCZs64p7VSfchXKfvl7CHq8VpHzzrE-2Fz6tZg-3D-3D">
<img src="https://static.figma.com/uploads/fd222b164c8e5d3814c3cfb3476d3a32ed159390" width="65" style="
width: 65px;
max-width: 65px;
font-size: 22px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
vertical-align: top;
line-height: 24px;
background-color: #ffffff;
color: #000;
text-align: center;
" alt="Figma"></a>
</td>
</tr>
<tr>
<td class="wi-100p pb-30" align="center" style="padding: 0 0 52px">
<img src="https://static.figma.com/uploads/a304018605bcb9fef4e437c9baaffe69ca19d792" width="392" style="width: 392px; vertical-align: top" alt="">
</td>
</tr>
<tr>
<td class="pb-30 plr-8 fs-24 lh-28" align="center" style="
padding-bottom: 56px;
font-size: 24px;
line-height: 29px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
">
You have a new comment on <strong>Material UI Sync</strong>
</td>
</tr>

<tr>
<td class="ptb-20 plr-25" style="
padding: 32px;
border: 2px solid #000;
border-radius: 8px;
">
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td width="28" style="padding-right: 8px">
<a href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsT6E0q8JamXppgg41V95-2FCT5nvB-2B9PboETbINvrCMatkYjcMKm81a1VwwEGm73u1tg-3D-3DYIMu_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2IEKsYWjkDOI0BcvC-2B4WI8KYaugDL1hVspEdVG-2FG3RG8xG5mEXdOrPRgA7HR-2BhKZnhq3QfPoL-2BitRO2S2ppTQTU9HwhT8e6cX05zZmzwO4QkHL4KRt-2FneBjZ7xbZKSILIdHepmXLy4r3XcQoda0epBQnDgxx6QsyHKobeD1NB1IXRFvQx4zHxhiW3f-2BxTb0TNdUCRKtY5WH4SMip0tAn0NJIvIrxdXUFrOx6hDxqcykSSvLqziRXA0lhWSKL5zfentSd10V5ACuwkym377z7RlXpHvVJclUJ1kuppbu5NJnQ-3D-3D"><img src="https://s3-alpha.figma.com/profile/c885606e-4504-406f-9d94-a9f275409964" style="
width: 24px;
border-radius: 50%;
vertical-align: middle;
" alt=""></a>
</td>
<td style="
font-weight: bold;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #000;
vertical-align: middle;
">
<a style="text-decoration: none" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsT6E0q8JamXppgg41V95-2FCT5nvB-2B9PboETbINvrCMatkYjcMKm81a1VwwEGm73u1tg-3D-3DsdQR_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2IEKsYWjkDOI0BcvC-2B4WI8d22iZApdgjBL5-2BmUa-2FODa8USENpRhnuhjjcOgqCzn0f9YcWh3NDDvJVj47kNTWSrLb-2B-2B4zJ3GfULHAXV1aES5FlzvnBeqqsCGbKVdmXWwAVAFHt47DtTJJLg253nDMnmlhL9XRKuY-2FLADNFyk-2BysdQOHvtrAfySAVYXMYwBS8mPxsYIPtOmrwp0liGOklF0THXbjap7Eba-2FAzN-2FtE1AG5FAiS3TzOVPP-2BYAcSIcOFOocR3b3b1706XxPoTgKHDmyxBtYZvZl7nTnD946fiJriw-3D-3D">Paul Whelan</a>
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td style="
padding-top: 12px;
font-weight: 350;
font-size: 18px;
line-height: 25px;
font-family: 'Whyte', Arial, Helvetica, sans-serif;
color: #000;
vertical-align: middle;
color: #000;
">
Doesn't work very well. Only showing x3 components (when more have been customised) and some don't even display inside the Storybook preview. For example, the button component (in light or dark) is empty, there is no button.
</td>
</tr>
</table>
</td>
</tr>
<tr>
<td class="pb-30" style="padding-top: 24px">
<table width="223" align="center" style="margin: 0 auto" cellpadding="0" cellspacing="0">
<tr>
<td class="active-t" align="center" style="
background: #000;
mso-padding-alt: 15px;
font: bold 18px/22px Arial, Helvetica, sans-serif;
border-radius: 8px;
">
<a style="
font-weight: bold;
font-size: 18px;
line-height: 23px;
font-family: 'Whyte', Arial, Helvetica,
sans-serif;
color: #fff;
text-decoration: none;
display: block;
padding: 15px;
" href="https://click.figma.com/ls/click?upn=u001.Y4GnNWhdnCDA1MWI-2FhIyfOSqzSOOn-2BuE-2BZrF9-2BcnUGiivhcOhY3M9uAFq63kbTUtR394Qn5A4XzkUEvl-2ByqtsQUnAiW-2Fjbz2GvSq7t8F63jF1WCuD4lA4X-2Bc0M1eJt2uzDm0i9LyHiCF6p73KAb-2Fzw-3D-3DHZ33_xN10UwO6-2Fkhj0B0Np2dbKlrPgpHJJ0Hhvw34FWYNgP2IEKsYWjkDOI0BcvC-2B4WI8C9qqGIq0kqDsLUxyMweiNs6Y0mKQj-2Bk607FDNzaDUkBbK2t76UorJnfmTHP-2FYQM4c3fM5XYStfLvcjC7YZxoKYG-2BXdBe5OkLXKmpuUCLriwmO21uGPnWpqVbSbFTXRy2DgyZRkEyNkiFtb4n2vtJ42bMIkxNJDTeSo21vMI9D1rFJ8wUXetw9bwea915W-2F4LouzRJsBoNAOvMZM5N3s2MBmU-2BzemWoVHWME0KrObSHzwbCLBm6WQjvL8Y0-2B-2FE0sNBFJY6adCy-2BRYsMzr-2Fyvp6w-3D-3D">Reply to comment</a>
</td>
</tr>
</table>
</td>
</tr>

**Comment by oliviertassinari** [comment] 2024-10-03 23:30
Closing this as a duplicate of #337

**Comment by oliviertassinari** [comment] 2024-10-03 23:31
Duplicate of #337

**Closed by oliviertassinari** 2024-10-03 23:30 UTC
Labels: figma, bug 🐛, duplicate, scope: sync
